name: gmail spam bot
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip
      - run: |
          cat <<'EOF' > send.py
          import smtplib, os
          from email.mime.multipart import MIMEMultipart
          from email.mime.text import MIMEText
          from email.mime.base import MIMEBase
          from email import encoders

          sender   = os.getenv("MAIL_USER")
          password = os.getenv("MAIL_PASS")
          receiver = os.getenv("MAIL_TO")
          subject  = os.getenv("MAIL_SUBJECT")
          file_path = "grass.png"

          msg = MIMEMultipart()
          msg["From"]    = sender
          msg["To"]      = receiver
          msg["Subject"] = subject
          msg.attach(MIMEText("Your header text here", "plain"))

          with open(file_path, "rb") as f:
              part = MIMEBase("application", "octet-stream")
              part.set_payload(f.read())
          encoders.encode_base64(part)
          part.add_header("Content-Disposition", f'attachment; filename="{file_path}"')
          msg.attach(part)

          with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
              server.login(sender, password)
              server.sendmail(sender, receiver, msg.as_string())
          EOF
      - run: python send.py
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
          MAIL_SUBJECT: ${{ secrets.MAIL_SUBJECT }}
