name: gmail spam bot
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          cat <<'EOF' > send.py
          import smtplib, os, time
          from email.mime.multipart import MIMEMultipart
          from email.mime.base import MIMEBase
          from email import encoders

          sender   = os.getenv("MAIL_USER")
          password = os.getenv("MAIL_PASS")
          receiver = os.getenv("MAIL_TO")
          file_path = "grass.png"
          subject = os.getenv("MAIL_SUBJECT")

          for i in range(1, 11):
              msg = MIMEMultipart()
              msg["From"]    = sender
              msg["To"]      = receiver
              msg["Subject"] = f"{subject} ({i}/10)"

              with open(file_path, "rb") as f:
                  part = MIMEBase("application", "octet-stream")
                  part.set_payload(f.read())
              encoders.encode_base64(part)
              part.add_header("Content-Disposition", f'attachment; filename="{file_path}"')
              msg.attach(part)

              with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                  server.login(sender, password)
                  server.sendmail(sender, receiver, msg.as_string())
              if i < 10:
                  time.sleep(2)
          EOF
      - run: python send.py
        env:
          MAIL_USER:    ${{ secrets.MAIL_USER }}
          MAIL_PASS:    ${{ secrets.MAIL_PASS }}
          MAIL_TO:      ${{ secrets.MAIL_TO }}
          MAIL_SUBJECT: ${{ secrets.MAIL_SUBJECT }}
